version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-01T01-11-10Z
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER:?Enter the Minio Root User}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?Enter the Minio Root Password}
    MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT:?Enter the Minio Console Port}
    MINIO_PORT: ${MINIO_PORT:?Enter the Minio Port}
  command: server --console-address ":${MINIO_CONSOLE_PORT}" /mnt/data
  ports:
    - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    - "${MINIO_PORT}:9000"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  photobox-minio1:
    <<: *minio-common
    container_name: photobox-minio1
    hostname: photobox-minio1
    volumes:
      - ./minio/data:/mnt/data
  photobox-app:
    environment:
      PORT: ${PORT:?Enter the Port Number to Run the app on}
      MINIO_HOST: photobox-minio1
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?Enter the Minio Access Key from the Admin Dashboard}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:?Enter the Minio Secret Key from the Admin Dashboard}
      G_TOKEN: ${G_TOKEN:?Enter the Guilded Token}
    build: 
      context: .
      dockerfile: ./docker/dev/app.dockerfile
    container_name: photobox-app
    volumes:
      - ./app:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - photobox-minio1
